"""Step 4 — tests for the pantry service.

Each test asks for the `session` fixture (a fresh in-memory DB from conftest.py).
Do not edit this file.
"""

import pytest
from sqlmodel import Session

from pantry_pilot.models.enums import BaseUnit, Category, StockStatus, TrackingMode, TxnReason
from pantry_pilot.models.tables import Ingredient
from pantry_pilot.services.pantry import (
    add_ingredient,
    archive_ingredient,
    get_ingredient,
    list_ingredients,
    record_transaction,
    set_status,
)


def _add_chicken(session: Session) -> Ingredient:
    return add_ingredient(
        session,
        name="chicken",
        category=Category.PROTEIN,
        tracking_mode=TrackingMode.QUANTITY,
        base_unit=BaseUnit.GRAM,
    )


def _add_salt(session: Session) -> Ingredient:
    return add_ingredient(
        session,
        name="salt",
        category=Category.STAPLE,
        tracking_mode=TrackingMode.PRESENCE,
        status=StockStatus.OK,
    )


def test_add_quantity_ingredient(session: Session) -> None:
    chicken = _add_chicken(session)
    assert chicken.id is not None          # saved -> the DB assigned an id
    assert chicken.on_hand == 0            # a new QUANTITY item starts empty
    assert chicken.status is None


def test_add_presence_ingredient(session: Session) -> None:
    salt = _add_salt(session)
    assert salt.id is not None
    assert salt.status is StockStatus.OK
    assert salt.on_hand is None            # PRESENCE items have no numeric stock


def test_quantity_without_base_unit_is_rejected(session: Session) -> None:
    with pytest.raises(ValueError):
        add_ingredient(
            session,
            name="rice",
            category=Category.CARB,
            tracking_mode=TrackingMode.QUANTITY,
        )


def test_presence_without_status_is_rejected(session: Session) -> None:
    with pytest.raises(ValueError):
        add_ingredient(
            session,
            name="pepper",
            category=Category.STAPLE,
            tracking_mode=TrackingMode.PRESENCE,
        )


def test_record_transaction_recomputes_on_hand(session: Session) -> None:
    chicken = _add_chicken(session)
    record_transaction(session, chicken, change_amount=800, reason=TxnReason.RESTOCK)
    record_transaction(session, chicken, change_amount=-200, reason=TxnReason.CONSUME)
    assert chicken.on_hand == 600          # 800 - 200, summed from the ledger


def test_record_transaction_on_presence_item_is_rejected(session: Session) -> None:
    salt = _add_salt(session)
    with pytest.raises(ValueError):
        record_transaction(session, salt, change_amount=100, reason=TxnReason.RESTOCK)


def test_get_ingredient_finds_by_name(session: Session) -> None:
    _add_chicken(session)
    found = get_ingredient(session, "chicken")
    assert found is not None
    assert found.name == "chicken"
    assert get_ingredient(session, "does-not-exist") is None


def test_list_ingredients_hides_archived_by_default(session: Session) -> None:
    _add_chicken(session)
    salt = _add_salt(session)
    archive_ingredient(session, salt)

    active_names = [i.name for i in list_ingredients(session)]
    assert "chicken" in active_names
    assert "salt" not in active_names                       # archived -> hidden

    all_names = [i.name for i in list_ingredients(session, include_archived=True)]
    assert "salt" in all_names                              # ...unless you ask for it


def test_archive_ingredient_soft_deletes(session: Session) -> None:
    salt = _add_salt(session)
    archive_ingredient(session, salt)
    assert salt.is_active is False
    assert salt.archived_at is not None


def test_set_status_updates_presence_item(session: Session) -> None:
    salt = _add_salt(session)
    set_status(session, salt, StockStatus.LOW)
    assert salt.status is StockStatus.LOW


def test_set_status_on_quantity_item_is_rejected(session: Session) -> None:
    chicken = _add_chicken(session)
    with pytest.raises(ValueError):
        set_status(session, chicken, StockStatus.OK)
