"""Step 3 — tests for the table models (structure + defaults).

RED FIRST: fails until you write src/pantry_pilot/models/tables.py.
These check the models build and have sane defaults. Persistence (insert/read,
FK enforcement) and the QUANTITY/PRESENCE invariant are tested later.
Do not edit this file.
"""

from datetime import datetime

from pantry_pilot.models.enums import (
    BaseUnit,
    Category,
    StockStatus,
    TrackingMode,
    TxnReason,
)
from pantry_pilot.models.tables import Ingredient, PantryTransaction


def test_build_a_quantity_ingredient() -> None:
    ing = Ingredient(
        name="chicken",
        category=Category.PROTEIN,
        tracking_mode=TrackingMode.QUANTITY,
        base_unit=BaseUnit.GRAM,
        on_hand=800,
    )
    assert ing.id is None                 # unsaved -> the DB assigns the id on insert
    assert ing.name == "chicken"
    assert ing.category is Category.PROTEIN
    assert ing.base_unit is BaseUnit.GRAM
    assert ing.on_hand == 800
    assert ing.status is None             # a QUANTITY item carries no status
    assert ing.is_active is True          # default
    assert isinstance(ing.created_at, datetime)
    assert isinstance(ing.updated_at, datetime)


def test_build_a_presence_ingredient() -> None:
    salt = Ingredient(
        name="salt",
        category=Category.STAPLE,
        tracking_mode=TrackingMode.PRESENCE,
        status=StockStatus.OK,
    )
    assert salt.status is StockStatus.OK
    assert salt.base_unit is None         # a PRESENCE item has no unit/quantity
    assert salt.on_hand is None
    assert salt.is_active is True


def test_build_a_transaction() -> None:
    txn = PantryTransaction(
        ingredient_id=1,
        change_amount=-200,
        reason=TxnReason.CONSUME,
    )
    assert txn.id is None                  # unsaved -> the DB assigns the id
    assert txn.ingredient_id == 1          # points at the ingredient this txn is about
    assert txn.change_amount == -200       # signed: negative = used some
    assert txn.reason is TxnReason.CONSUME
    assert txn.note is None
    assert isinstance(txn.created_at, datetime)


def test_transaction_amount_is_signed() -> None:
    restock = PantryTransaction(ingredient_id=1, change_amount=500, reason=TxnReason.RESTOCK)
    consume = PantryTransaction(ingredient_id=1, change_amount=-200, reason=TxnReason.CONSUME)
    assert restock.change_amount == 500    # positive = added stock
    assert consume.change_amount == -200   # negative = removed stock
