"""Step 2a — tests for the env-driven Settings object.

RED FIRST: these fail until you write src/pantry_pilot/core/config.py.
Your job is to make them green. Do not edit this file.
"""

from pathlib import Path

import pytest

from pantry_pilot.core.config import Settings


def test_defaults_point_at_local_db() -> None:
    settings = Settings()
    assert settings.db_path == Path("data/pantry.db")
    assert settings.echo_sql is False


def test_database_url_is_a_sqlite_url() -> None:
    settings = Settings()
    # SQLAlchemy speaks URLs, not file paths. Relative path -> three slashes.
    assert settings.database_url == "sqlite:///data/pantry.db"


def test_env_vars_override_defaults(monkeypatch: pytest.MonkeyPatch) -> None:
    # The PANTRY_ prefix maps PANTRY_DB_PATH -> the db_path field, and
    # pydantic coerces the string "true" into a real bool.
    monkeypatch.setenv("PANTRY_DB_PATH", "/tmp/pantry-test.db")
    monkeypatch.setenv("PANTRY_ECHO_SQL", "true")

    settings = Settings()

    assert settings.db_path == Path("/tmp/pantry-test.db")
    assert settings.echo_sql is True
    # An ABSOLUTE path brings its own leading slash -> four slashes total.
    assert settings.database_url == "sqlite:////tmp/pantry-test.db"


def test_anthropic_api_key_reads_standard_env_var(monkeypatch: pytest.MonkeyPatch) -> None:
    # The SDK's own convention is ANTHROPIC_API_KEY (no PANTRY_ prefix), so we
    # read that exact name via validation_alias.
    monkeypatch.setenv("ANTHROPIC_API_KEY", "sk-ant-test-123")
    settings = Settings()
    assert settings.anthropic_api_key == "sk-ant-test-123"


def test_anthropic_api_key_defaults_to_empty(monkeypatch: pytest.MonkeyPatch) -> None:
    # No key in the environment -> a safe empty default (we fail loudly later, not here).
    monkeypatch.delenv("ANTHROPIC_API_KEY", raising=False)
    settings = Settings()
    assert settings.anthropic_api_key == ""
