"""Step 4 — tests for the pantry service.

RED FIRST: fails until you write src/pantry_pilot/services/pantry.py.
Each test asks for the `session` fixture (a fresh in-memory DB from conftest.py).
Do not edit this file.
"""

import pytest
from sqlmodel import Session

from pantry_pilot.models.enums import BaseUnit, Category, StockStatus, TrackingMode
from pantry_pilot.services.pantry import add_ingredient


def test_add_quantity_ingredient(session: Session) -> None:
    chicken = add_ingredient(
        session,
        name="chicken",
        category=Category.PROTEIN,
        tracking_mode=TrackingMode.QUANTITY,
        base_unit=BaseUnit.GRAM,
    )
    assert chicken.id is not None          # saved -> the DB assigned an id
    assert chicken.on_hand == 0            # a new QUANTITY item starts empty
    assert chicken.status is None


def test_add_presence_ingredient(session: Session) -> None:
    salt = add_ingredient(
        session,
        name="salt",
        category=Category.STAPLE,
        tracking_mode=TrackingMode.PRESENCE,
        status=StockStatus.OK,
    )
    assert salt.id is not None
    assert salt.status is StockStatus.OK
    assert salt.on_hand is None            # PRESENCE items have no numeric stock


def test_quantity_without_base_unit_is_rejected(session: Session) -> None:
    # The QUANTITY/PRESENCE invariant lives HERE, in the service.
    with pytest.raises(ValueError):
        add_ingredient(
            session,
            name="rice",
            category=Category.CARB,
            tracking_mode=TrackingMode.QUANTITY,
            # base_unit missing -> must raise
        )


def test_presence_without_status_is_rejected(session: Session) -> None:
    with pytest.raises(ValueError):
        add_ingredient(
            session,
            name="pepper",
            category=Category.STAPLE,
            tracking_mode=TrackingMode.PRESENCE,
            # status missing -> must raise
        )
