"""Step 3b — tests for the Ingredient table model (structure + defaults).

RED FIRST: fails until you write src/pantry_pilot/models/tables.py.
These check the model builds and has sane defaults. Persistence (insert/read,
FK enforcement) and the QUANTITY/PRESENCE invariant are tested later.
Do not edit this file.
"""

from datetime import datetime

from pantry_pilot.models.enums import (
    BaseUnit,
    Category,
    StockStatus,
    TrackingMode,
)
from pantry_pilot.models.tables import Ingredient


def test_build_a_quantity_ingredient() -> None:
    ing = Ingredient(
        name="chicken",
        category=Category.PROTEIN,
        tracking_mode=TrackingMode.QUANTITY,
        base_unit=BaseUnit.GRAM,
        on_hand=800,
    )
    assert ing.id is None                 # unsaved -> the DB assigns the id on insert
    assert ing.name == "chicken"
    assert ing.category is Category.PROTEIN
    assert ing.base_unit is BaseUnit.GRAM
    assert ing.on_hand == 800
    assert ing.status is None             # a QUANTITY item carries no status
    assert ing.is_active is True          # default
    assert isinstance(ing.created_at, datetime)
    assert isinstance(ing.updated_at, datetime)


def test_build_a_presence_ingredient() -> None:
    salt = Ingredient(
        name="salt",
        category=Category.STAPLE,
        tracking_mode=TrackingMode.PRESENCE,
        status=StockStatus.OK,
    )
    assert salt.status is StockStatus.OK
    assert salt.base_unit is None         # a PRESENCE item has no unit/quantity
    assert salt.on_hand is None
    assert salt.is_active is True
