"""Step 3a — tests for the domain enums (the vocabulary the tables will use).

RED FIRST: these fail until you write src/pantry_pilot/models/enums.py.
Make them green. Do not edit this file.
"""

from pantry_pilot.models.enums import (
    BaseUnit,
    Category,
    StockStatus,
    TrackingMode,
    TxnReason,
)


def test_category_values() -> None:
    assert {c.value for c in Category} == {"protein", "carb", "green", "staple"}


def test_tracking_mode_values() -> None:
    assert {m.value for m in TrackingMode} == {"quantity", "presence"}


def test_base_unit_values() -> None:
    assert {u.value for u in BaseUnit} == {"each", "gram", "milliliter"}


def test_stock_status_values() -> None:
    assert {s.value for s in StockStatus} == {"out", "low", "ok"}


def test_txn_reason_values() -> None:
    assert {r.value for r in TxnReason} == {
        "initial",
        "restock",
        "consume",
        "discard",
        "adjust",
    }


def test_members_behave_like_strings() -> None:
    # Because the enums inherit from (str, Enum), a member IS a string.
    assert Category.PROTEIN.value == "protein"
    assert isinstance(Category.PROTEIN, str)
